# frozen_string_literal: true

development:
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/2') %>
  channel_prefix: orders_service_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/2') %>
  channel_prefix: orders_service_production
